### ISSUE TITLE
Compilation error: Implementation limit exceeded

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#11] opened 2020-05-21 08:20 UTC
Some people get this error while instantiating a WASM module, all of them on Windows, e.g. [see here](https://twitter.com/cr1901/status/1263382082287472647). Unfortunately it is quite opaque and I'm not really sure where to go from here, especially since wasmtime-py ignores `RUST_LOG`. How do I debug this?

**Comment by tschneidereit** [comment] 2020-05-21 10:20
That's probably bytecodealliance/wasmtime#1734, so should hopefully be fixed once that PR lands.

@alexcrichton would it be feasible to have wasmtime-py respect `RUST_LOG`?

**Comment by alexcrichton** [comment] 2020-05-21 14:28
I've opened https://github.com/bytecodealliance/wasmtime/pull/1737 to get `RUST_LOG` working, and otherwise @tschneidereit is right that PR should fix the underlying issue too!

**Comment by alexcrichton** [comment] 2020-05-21 16:06
Ok I'm going to close this in favor of https://github.com/bytecodealliance/wasmtime/pull/1734 and the upstream issue at https://github.com/bytecodealliance/wasmtime/issues/1587, since I believe those should cover the issues here.

**Closed by alexcrichton** 2020-05-21 16:06 UTC

**Comment by peterhuene** [comment] 2020-05-22 19:07
@whitequark the fix for this issue was just merged.  Please let me know if you're still running into an issue on Windows.  Thanks!

**Comment by whitequark** [comment] 2020-05-22 19:44
I can confirm this fixes the Windows issue.

@alexcrichton Is there a chance we can have a wasmtime release?

**Comment by alexcrichton** [comment] 2020-05-22 20:04
Sure yeah, I pushed a [0.16.1 tag](https://github.com/bytecodealliance/wasmtime-py/tree/0.16.1) which is the exact same as the 0.16.0 tag but should download the latest copies of the C API. We've had some breaking API changes so I'm going to hold off until 0.17.0 of wasmtime itself before publishing that for this extension.

CI isn't running, however, so I'm going to need to debug that...

**Comment by alexcrichton** [comment] 2020-05-22 22:40
Ok published now!

**Comment by cr1901** [comment] 2020-05-23 05:43
I can confirm that `wasmtime-py` and `wasmtime` are fixed on my end on `mingw` _via a manual install_. Just for the sake of knowing, is there any particular reason that if you install manually you have to download `wasmtime` into your source directory instead of `wasmtime` being installed into `site-packages`?
![image](https://user-images.githubusercontent.com/6418027/82722664-c0afde00-9c96-11ea-803b-e11b1645b5be.png)

**Comment by alexcrichton** [comment] 2020-05-23 18:42
The wasmtime dynamic library needs to be downloaded to wherever wasmtime-py is installed to, and it you're manually installing it that may explain the oddness?
